### ISSUE TITLE
additional directories for `ghqrs list`

### ISSUE THREAD

**Issue by ubnt-intrepid** [ubnt-intrepid/ghqrs#10]
```toml
[[search]]
path = "~/vim/plugged"
depth = 1

[[search]]
path = "~/.dotfiles"
root = true
```
